#!/usr/bin/env bash

# Example: Pure Firefox KIOSK mode (no desktop environment)
docker run -it \
    --rm \
    --hostname="$(hostname)" \
    --publish="3389:3389/tcp" \
    --name="remote-desktop-kiosk" \
    --shm-size="1g" \
    --env "FIREFOX_HOME=https://google.com" \
    --env "FIREFOX_KIOSK=true" \
    --env "KIOSK_LOCKDOWN=true" \
    docker-remote-desktop:latest